# Generated by Django 4.2.7 on 2023-11-15 15:37

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cartorderitems_invoice_no_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='mcat', unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Main Categories',
            },
        ),
    ]
