# Generated by Django 4.2.7 on 2023-11-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(default=1, upload_to='main_category'),
            preserve_default=False,
        ),
    ]
