# Generated by Django 4.2.7 on 2023-11-18 15:15

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_maincategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='tcat', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='top_category')),
            ],
            options={
                'verbose_name_plural': 'Main Categories',
            },
        ),
        migrations.AddField(
            model_name='maincategory',
            name='top_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topcategory'),
        ),
    ]
