# Generated by Django 4.2.7 on 2023-11-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_topcategory_maincategory_top_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topcategory',
            options={'verbose_name_plural': 'Top Categories'},
        ),
        migrations.RemoveField(
            model_name='topcategory',
            name='image',
        ),
    ]
