# Generated by Django 4.2.7 on 2023-11-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_colour_remove_product_old_price_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colour',
            name='product',
        ),
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
    ]
