# Generated by Django 4.2.7 on 2023-11-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_colour_product_remove_size_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=999999999),
        ),
    ]
