# Generated by Django 4.2.7 on 2023-11-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_f_name_address_name_remove_address_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='invoice_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
