# Generated by Django 4.2.7 on 2023-12-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_coupon_minimun_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='minimun_amount',
            new_name='minimum_amount',
        ),
    ]
