# Generated by Django 4.2.7 on 2023-12-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_cartorder_refund_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='status',
            field=models.CharField(blank=True, choices=[('return_requested', 'Return Requested'), ('refund_requested', 'Refund Requested'), ('return_approved', 'Return Approved'), ('refund_approved', 'Refund Approved')], default=None, max_length=30, null=True),
        ),
    ]
