# Generated by Django 4.2.7 on 2023-12-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_cartorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='status',
            field=models.CharField(blank=True, choices=[('return_requested', 'Return Requested'), ('refund_requested', 'Refund Requested'), ('return_approved', 'Return Approved'), ('refund_approved', 'Refund Approved')], default=None, max_length=30, null=True),
        ),
    ]
