# Generated by Django 4.2.7 on 2023-12-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='status',
            field=models.CharField(blank=True, choices=[('return_requested', 'Return Requested'), ('refund_requested', 'Refund Requested'), ('return_approved', 'Return Approved'), ('refund_approved', 'Refund Approved'), ('refund_successful', 'Refund Successful')], default=None, max_length=30, null=True),
        ),
    ]
