# Generated by Django 4.2.7 on 2023-12-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_cartorder_applied_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupon'),
        ),
    ]
