# Generated by Django 4.2.7 on 2023-12-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_cartorder_applied_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='applied_coupon',
        ),
    ]
