# Generated by Django 4.2.7 on 2023-12-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_cartorder_applied_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
