# Generated by Django 4.2.7 on 2023-11-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='f_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='s_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
